<span style="font-size: 100%; ">論文“井元佑介, 超双対数に基づく高階微分計算手法の開発と応用, 応用数理, 2024.”における超双対数の行列表示を用いた微分計算の計算例</span>

# 超双対数単位と超双対数空間上の関数の定義 

In [12]:
# coding: utf-8
import numpy as np
import math
from functools import reduce

# def Setting(n):
#     global nHDN
#     nHDN = n
#     global HDN
#     HDN = [[0 for i in range(nHDN)] for j in range(nHDN)]
#     HDN[0][0] = np.matrix([[0, 1], [0, 0]])
#     for k in range(nHDN - 1):
#         for l in range(k + 1):
#             HDN[k + 1][l] = np.matrix([[0 for i in range(pow(2, k + 2))] for j in range(pow(2, k + 2))])
#             for i in range(pow(2, k + 1)):
#                 for j in range(pow(2, k + 1)):
#                     HDN[k + 1][l][i, j] = HDN[k][l][i, j]
#                     HDN[k + 1][l][i + pow(2, k + 1), j] = 0.
#                     HDN[k + 1][l][i, j + pow(2, k + 1)] = 0.
#                     HDN[k + 1][l][i + pow(2, k + 1), j + pow(2, k + 1)] = HDN[k][l][i, j]
#         HDN[k + 1][k + 1] = np.matrix([[0 for i in range(pow(2, k + 2))] for j in range(pow(2, k + 2))])
#         for i in range(pow(2, k + 1)):
#             for j in range(pow(2, k + 1)):
#                 if i == j:
#                     HDN[k + 1][k + 1][i, j + pow(2, k + 1)] = 1.
#     global ID
#     ID = np.matrix(np.eye(2**nHDN))



def Setting(n):
    global nHDN
    nHDN = n
    global HDN
    E_11 = np.array([[0, 1], [0, 0]], dtype=float)
    I_2 = np.eye(2)
    HDN = np.empty(nHDN, dtype=object)
    for i in range(nHDN):
        kron_list = [E_11 if j == nHDN - i - 1 else I_2 for j in range(nHDN)]
        HDN[i] = reduce(np.kron, kron_list)
    global ID
    ID = np.array(np.eye(2**nHDN))

def Deriv(Mat, k):
    if 0 <= k <= nHDN:
        return Mat[0,2**k-1]
    else:
        return "error"

def prod(Mat1,Mat2):
    return np.dot(Mat1,Mat2)

def const():
    return ID


def Hini(x):
    return  x * ID + np.sum(HDN,axis=0)



def Hsin(Mat):
    a = Mat[0,0]
    Q = Mat-a*ID
    val = np.sin(a)*ID
    for i in range(nHDN):
        val += (Q**(i+1))/math.factorial(i+1)*(
            (-1)**(((i+1)//2)%4)*((i+2)%2)*math.sin(a)
            +(-1)**((i//2)%4)*(i+1)%2)*math.cos(a)
    return  val

def Hcos(Mat):
    a = Mat[0,0]
    Q = Mat-a*ID
    val = math.cos(a)*ID
    for i in range(nHDN):
        val += (Q**(i + 1)) * (
                    pow(-1, ((i + 1) // 2) % 4) * ((i + 2) % 2) * math.cos(Mat[0, 0]) + pow(-1, ((i + 2) // 2) % 4) * (
                        (i + 1) % 2) * math.sin(Mat[0, 0])) / math.factorial(i + 1)
    return  val


def Hexp(Mat):
    val = math.exp(Mat[0, 0]) * ID
    for i in range(nHDN):
        val += ((Mat - Mat[0, 0] * ID) ** (i + 1)) * math.exp(Mat[0, 0]) / math.factorial(i + 1)
    return  val


def Hlog(Mat):
    val = math.log(Mat[0, 0]) * ID
    for i in range(nHDN):
        val += ((Mat - Mat[0, 0] * ID) ** (i + 1)) * (pow(-1, i)) * (Mat[0, 0] ** (-i - 1)) / (i + 1)
    return  val


def Hpow(Mat, m):
    coef = 1
    val = math.pow(Mat[0, 0], m) * ID
    for i in range(nHDN):
        coef *= m-i
        val += coef*((Mat - Mat[0, 0] * ID) ** (i + 1)) * math.pow(Mat[0, 0], m - i - 1) / math.factorial(i + 1)
    return  val


def HiniMult(x,k,Jn):
    val = x * ID
    for i in range(nHDN):
        if Jn[i] == k:
            val += HDN[i]
    return  val

In [13]:
nHDN = 12
E_11 = np.matrix([[0, 1], [0, 0]],dtype=float)
I_2 = np.eye(2)
HDN = np.empty(nHDN,dtype=object)
for i in range(nHDN):
    HDN[i] = 1
    for j in range(nHDN):
        if j==nHDN-i-1:
            HDN[i] = np.kron(HDN[i],E_11)
        else:
            HDN[i] = np.kron(HDN[i],I_2)

HDN

array([matrix([[0., 1., 0., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 0.],
               ...,
               [0., 0., 0., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 1.],
               [0., 0., 0., ..., 0., 0., 0.]]),
       matrix([[0., 0., 1., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 0.],
               ...,
               [0., 0., 0., ..., 0., 0., 1.],
               [0., 0., 0., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 0.]]),
       matrix([[0., 0., 0., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 0.],
               ...,
               [0., 0., 0., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 0.]]),
       matrix([[0., 0., 0., ..., 0., 0., 0.],
               [0., 0., 0., ..., 0., 0., 0.],
              

In [14]:
import numpy as np
from functools import reduce

nHDN = 3
E_11 = np.array([[0, 1], [0, 0]], dtype=float)
I_2 = np.eye(2)

# 初期化
HDN = np.empty(nHDN, dtype=object)

# 高速な行列演算を利用して HDN を生成
for i in range(nHDN):
    kron_list = [E_11 if j == nHDN - i - 1 else I_2 for j in range(nHDN)]
    HDN[i] = reduce(np.kron, kron_list)

print(HDN)

[array([[0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
 array([[0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
 array([[0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.,

In [15]:
import numpy as np

nHDN = 2
E_11 = np.array([[0, 1], [0, 0]], dtype=float)
I_2 = np.eye(2)

# 行列のリストを作成
kron_list = [E_11 if j == nHDN - i - 1 else I_2 for i in range(nHDN) for j in range(nHDN)]

# 高速な行列演算を利用して HDN を生成
HDN = np.linalg.multi_dot(kron_list[::-1])

# 必要であれば、HDN を出力する
print(HDN)


[[0. 0.]
 [0. 0.]]


$f(x)=sin(x)$の$x=0$での高階微分値の計算

In [23]:
HDN,ID
np.sum(HDN,axis=0)

array([[0., 1., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
# 微分階数 (超双対数の次数)
n = 3

#　初期設定 (超双対数単位の構成)
Setting(n)

# 関数の定義
def Func(x):
    return Hsin(Hini(x))

# value
x = 0


# 4th derivatives of Func on x
for i in range(n+1):
    print(i,"-derivative(s)=",Deriv(Func(x),i))

0 -derivative(s)= 0.0
1 -derivative(s)= 1.1666666666666667
2 -derivative(s)= 0.0
3 -derivative(s)= 0.0


# 付録Bの例

$f(x)=e^{\cos(x_1)+x_2^2}$の二階偏微分$\partial_1\partial_2 f(x)$の計算

In [17]:
Setting(2)
HDN

array([array([[0., 1., 0., 0.],
              [0., 0., 0., 0.],
              [0., 0., 0., 1.],
              [0., 0., 0., 0.]]), array([[0., 0., 1., 0.],
                                         [0., 0., 0., 1.],
                                         [0., 0., 0., 0.],
                                         [0., 0., 0., 0.]])], dtype=object)

In [18]:
# 微分階数 (超双対数の次数)
n = 2

#　初期設定 (超双対数単位の構成)
Setting(n)

## One-variable function ##
# f(x) = exp(sin(sqrt(x)+3*x))*log(cos^2(x)+0.5)
def Func(x):
    #return prod(Hexp(Hsin(Hpow(Hini(x),1/2)+3.*Hini(x))),Hlog(Hpow(Hcos(Hini(x)),2)+0.5*const()))
    return Hsin(Hini(x))

# value
x = 0


# 4th derivatives of Func on x
for i in range(n+1):
    print(i,"-derivative(s)=",Deriv(Func(x),i))

0 -derivative(s)= 0.0
1 -derivative(s)= 1.0
2 -derivative(s)= 0.0


In [19]:
## Multi-variables function ##
# multi-index for partial derivative
Jn = [0,0,1,2,2,0,0,1,2,2] # ∂x0∂x0∂x1∂x2∂x2∂x0∂x0∂x1∂x2∂x2
n = len(Jn)
Setting(n)


# f(x0,x1,x2) = exp(sin(sqrt(x0)+3*x1))*log(cos^2(x2)+0.5)
def MultiFunc(x0,x1,x2):
    return prod(Hexp(Hsin(Hpow(HiniMult(x0,0,Jn),1/2)+3.*HiniMult(x1,1,Jn))),Hlog(Hpow(Hcos(HiniMult(x2,2,Jn)),2)+0.5*const()))


# values
x0 = 0.5*math.pi
x1 = 0.25*math.pi
x2 = 2.


# 4th partial derivatives of MultiFunc on (x0,x1,x2)
for i in range(n+1):
    print(i,"-partial derivative(s)=",Deriv(MultiFunc(x0,x1,x2),i))


0 -partial derivative(s)= -0.2520792083298674
1 -partial derivative(s)= 0.07323225947950249
2 -partial derivative(s)= 0.0
3 -partial derivative(s)= 0.0
4 -partial derivative(s)= 0.0
5 -partial derivative(s)= 0.0
6 -partial derivative(s)= 0.0
7 -partial derivative(s)= 0.0
8 -partial derivative(s)= 0.0
9 -partial derivative(s)= 0.0
10 -partial derivative(s)= 0.0
